cc_library(
    name = "tictactoe",
    hdrs = ["tictactoe.hh",],
    srcs = ["tictactoe.cc"],
    deps = []
)

cc_binary(
    name = "tictactoe_main",
    srcs = ["tictactoe_main.cc"],
    deps = [":tictactoe"],
)
